[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/" 

[network]
port = 30307
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"

[rpc]
port = 8551
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts"]
interface = "all"
cors = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0xa35aa7e43032f5cc32ee48c92ca3dc5b9f1e745d"  
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true
