[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/" 

[network]
port = 30303
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"
# Override the bootnodes from selected chain file.
#bootnodes = ["enode://XXX@localhost:30300", "enode://XXXX@localhost:30301"]
# Enable or disable new peers discovery.
#discovery = false[rpc]

[rpc]
port = 8547
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts"]
interface = "all"
cors = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0x3926bd6786eb6f676437cc2e9a87613980684bca"
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true
