[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/"

[network]
port = 30308
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"

[rpc]
port = 8552
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts"]
interface = "all"
cors = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0xa432698065d2c7cead5a4ec53e6cf03cde7c8152"  
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true
